### ISSUE TITLE
Add CI Checker

### ISSUE THREAD

**Issue by Earlystarry** [HUSTSeclab/TranslateProject#11]
添加类似 [LCTT Workflow](https://gitee.com/link?target=https%3A%2F%2Fgithub.com%2FLCTT%2FTranslateProject%2Fblob%2Fmaster%2F.github%2Fworkflows%2Flctt-article-checker.yml)的 CI 流程，自动检查译文格式和来源。

**Comment by mudongliang** [comment]
1. 根据当前提交 PR 的用户，检查 frontmatter 是否正确。

这个要和当前的翻译流程有关系。
- 选题(status 为 collected): 要保证 status, title, author, collector, collected_date 这几个域都存在，同时 collector 应该和当前提交 PR 的 github id 一致。

```
status: collected
title: FILL_THE_TITLE_HERE
author: FILL_THE_AUTHOR_HERE
collector: FILL_YOUR_GITHUB_ID_HERE
collected_date: yyyymmdd(e.g., 20240224)
link: FILL_THE_LINK_HERE
```
- 翻译
    - 翻译申请（status为translating）：translator 应该和当前提交 PR 的 github id 一致。
    - 翻译提交（status为translated）：保证 translated_date 必须存在
- 校对：校对要求与翻译相同，只是状态改为 proofreading 和 proofread。
- 发布：校对要求与翻译相同，只是状态改为 published。

**Comment by inscripoem** [comment]
请问在检查的过程中需要确认`link`这一域的存在吗，我看上面的需求中没有提到，但是前端的代码中又对这一域有依赖，是否应该在`collected`阶段予以确认？

**Comment by mudongliang** [comment]
> 请问在检查的过程中需要确认`link`这一域的存在吗，我看上面的需求中没有提到，但是前端的代码中又对这一域有依赖，是否应该在`collected`阶段予以确认？

嗯，需要，这个字段会展示出来的
